services:
  - type: web
    name: solana-meme-bot
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python solana_meme_bot_final.py"
    pythonVersion: 3.10.13
